

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."test" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."test" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."test2" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."test2" OWNER TO "postgres";


ALTER TABLE "public"."test2" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test2_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."test3" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."test3" OWNER TO "postgres";


ALTER TABLE "public"."test3" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test3_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."test4" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."test4" OWNER TO "postgres";


ALTER TABLE "public"."test4" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test4_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."test5" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."test5" OWNER TO "postgres";


ALTER TABLE "public"."test5" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test5_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."test6" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."test6" OWNER TO "postgres";


ALTER TABLE "public"."test6" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test6_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."test7" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."test7" OWNER TO "postgres";


ALTER TABLE "public"."test7" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test7_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."test8" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."test8" OWNER TO "postgres";


ALTER TABLE "public"."test8" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test8_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."test" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."test_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."test2"
    ADD CONSTRAINT "test2_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test3"
    ADD CONSTRAINT "test3_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test4"
    ADD CONSTRAINT "test4_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test5"
    ADD CONSTRAINT "test5_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test6"
    ADD CONSTRAINT "test6_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test7"
    ADD CONSTRAINT "test7_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test8"
    ADD CONSTRAINT "test8_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."test"
    ADD CONSTRAINT "test_pkey" PRIMARY KEY ("id");



ALTER TABLE "public"."test" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test2" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test3" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test4" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test5" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test6" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test7" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."test8" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";








































































































































































GRANT ALL ON TABLE "public"."test" TO "anon";
GRANT ALL ON TABLE "public"."test" TO "authenticated";
GRANT ALL ON TABLE "public"."test" TO "service_role";



GRANT ALL ON TABLE "public"."test2" TO "anon";
GRANT ALL ON TABLE "public"."test2" TO "authenticated";
GRANT ALL ON TABLE "public"."test2" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test2_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test2_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test2_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."test3" TO "anon";
GRANT ALL ON TABLE "public"."test3" TO "authenticated";
GRANT ALL ON TABLE "public"."test3" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test3_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test3_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test3_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."test4" TO "anon";
GRANT ALL ON TABLE "public"."test4" TO "authenticated";
GRANT ALL ON TABLE "public"."test4" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test4_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test4_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test4_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."test5" TO "anon";
GRANT ALL ON TABLE "public"."test5" TO "authenticated";
GRANT ALL ON TABLE "public"."test5" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test5_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test5_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test5_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."test6" TO "anon";
GRANT ALL ON TABLE "public"."test6" TO "authenticated";
GRANT ALL ON TABLE "public"."test6" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test6_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test6_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test6_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."test7" TO "anon";
GRANT ALL ON TABLE "public"."test7" TO "authenticated";
GRANT ALL ON TABLE "public"."test7" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test7_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test7_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test7_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."test8" TO "anon";
GRANT ALL ON TABLE "public"."test8" TO "authenticated";
GRANT ALL ON TABLE "public"."test8" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test8_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test8_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test8_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."test_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."test_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."test_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";






























RESET ALL;
