name: Supabase Migration Sync

on:
  workflow_dispatch: # pode rodar manualmente
  push:
    paths:
      - "supabase/migrations/**" # dispara quando migrations mudarem

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v3


      - name: Login to Supabase
        run: npx supabase login --token ${{ secrets.SUPABASE_TOKEN }}

      - name: Configurar Supabase Project origem
        run: npx supabase link --project-ref ${{ secrets.PROJECT_X_REF_ID }} --password ${{ secrets.PROJECT_X_API_KEY }}

      - name: Tentar pegar migrações
        id: migrate_pull
        continue-on-error: true
        run: |
          set -e
          echo "🔄 Aplicando migrações..."
          npx supabase db pull -p ${{ secrets.PROJECT_X_API_KEY }}

      - name: Resolver inconsistências (se falhou)
        if: steps.migrate_pull.outcome == 'failure'
        run: |
          echo "⚠️ Erro ao aplicar migrações. Tentando reparar..."
          # Identificar a última migração no erro
          MIGRATION=$(npx supabase migration list --output json -p ${{ secrets.PROJECT_X_API_KEY }}  | jq -r '.[] | select(.status=="remote") | .id' | tail -n1)
          
          if [ -n "$MIGRATION" ]; then
            npx supabase migration repair --status reverted $MIGRATION
          fi

          echo "🔄 Tentando novamente aplicar migrações..."
          npx supabase db pull -p ${{ secrets.PROJECT_X_API_KEY }}

      
      - name: Commitar migrations
        run: |
          git config user.name "WallaceRodrigues07"
          git config user.email "wallace.rodrigues@baymetrics.com.br"
          git add supabase/migrations supabase/metadata
          git commit -m "Atualiza migrations a partir do banco remoto" || echo "Sem alterações para commitar"
          git push
